env:
  global:
  - CC_TEST_REPORTER_ID=1fd47627409af6283040c758f8d771a32e26204bd9a9bfbc22f219e5ac549bcc
  - secure: JSXgdpS1dT5VXDIG9ymnHz3iD6wD4pwfBRY4qBDw126STIRIBX0KwNRcEOlobHHFH4P3Qe8dTib8ut60E/ukoVw/CtERVpfrUPGow1cP/R+clTPkzvz351qADPvRBKAoVVD3wKkbhjmtfA+XLRckpUaQS/wPZ8GZ38t4D6i1W4gJeDKsgw7L4dWERtjLGaOndbKPzgcN1YFeUyJ0RJ6whk8cJ29gypMB5aWJO8OZyB7IVqUsJVmSEEAnD2Feuje2pfFniWA6g9Uo4jq0n8zOkxYKOqLJd3Wkt7JM2/jQZ2nVz56zadQxEcccoR7OTdX23WAI+lZPK0nM8+xSXc3sdLRgGAFHEE3xaBW3B30vDcjk7KleWGjnbgpQw8UrxJrUEH3lsNeZHSGZsHWjhMk3113AOCA3bVr9CewxEQR/MAiTJRTT9HVf2PRjgX/pjDN9qjdeYn/5G4yOv0xvTpl5O/CKN24TN0V+H4OjrcZQhbZ1gRLa1KeulTUDkAerQOC6jPTsKMWb6RYVSExU2fYWUJX7w379F7hVk9ami1GZ0sBPz1Foms//7Xyq4FZUAp2xZfQgdAKzfZPj2RHYigRAalyF52wxjC9GUZixpj9GbJdlXjytber0nHK0ju4Ipt2WdhWb92SGiglIbrewg1CmL4Og6kPOHIUB9TsaBTrvwBA=
language: ruby
cache:
- bundler
rvm:
- 2.5.6
before_script:
- bundle exec rake db:create
- bundle exec rake db:migrate
- bundle exec rake assets:precompile
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
deploy:
  provider: heroku
  api_key: 
    secure: opcOKSgrzyAa51ReyK4Q7clBEw4LVcSKfh+eEv0UssttM/EHsWYNxsb2q5KwPHr2FKbTRY3D6wL+igE3gSJJ9icyI8dPRkK6CsIeGRjAcdKUPIK0veAXianccSBtI9HMV/dsqA57LjpCxx/sD+BxIXa0MBG8OKmNUxy6QcNXrs8GbbyWbQnEPxpsVIpPm/aDdouEdeWNDcOHcKeRlJGa4NmnyZL8KZRmidqWVf7XAWNNeM2Z/Uv3bmpX9geXU7KlptDpjSo3dF0StoT2nROhcHqYRzFqAZ6iYdIeJhM8P1bLTMjyP4aw6ylPGZme7wpUQV97csLWunXFtycyBmoBH69tLk3d0WwnHSfU3FiNYi2Uh9BoODif0SXWqsm82TdMC7Tk7hlAAUGpN6uBpRmWXsmFZmSrVCauT2ifJsJGGVL/34vgpdEjUP0OKufxyi5+YeJ4+qs9qLN7nI382TJyvSdSw/HnUgo6JeUM8DIDndQmb+FwH5TAe0u4ilzgZWsz1FYeXVnLvrjivXUrz5VkNVth0N3Vd91fw0vrp8s0nFmzsmjizRc34Hh/LwTO5G96CDF2yAKe2aqzD/QNGFc9czD77SLHtuFqYwy6HHxzv9/kk8NsAFOHZ5YdffNo4Xm9yKzvvqnh2CReLoLKSt9NCh8jBzlruvazX5thb02Rn6M=
script:
- bundle exec rails db:migrate RAILS_ENV=test
- bundle exec rake
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
